#!/usr/bin/env python3
"""
Vectorize a Greek word in some reading fonts, for the about page.

The about page shows the same word in several reading fonts; drawn as SVG
paths, it downloads none of them. Each font is scaled like in `fonts.css`
(`size-adjust`: its lowercase as high as Inter's), so that the specimens
compare as in the application.

Writes `app/utils/fontSpecimens.ts`. Requires `pip install fonttools brotli
uharfbuzz`.

Usage: scripts/font-specimens.py
"""

import io
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "app/assets/fonts"
OUTPUT = ROOT / "app/utils/fontSpecimens.ts"

WORD = "λόγος"

# Name shown, file, `size-adjust` (cf. `fonts.css`).
SPECIMENS = [
    ("Bailly Book", "Gentium_Book_Plus/BaillyBook-Roman.subset.woff2", 1.176),
    ("GFS Didot", "GFS_Didot/GFS_Didot-Roman.woff2", 1.179),
    ("GFS NeoHellenic", "GFS_NeoHellenic/GFS_NeoHellenic-Roman.woff2", 1.387),
]

# The common frame, in thousandths of an em: from above the accents of the
# capitals to below the descenders (cf. the overflow noted in `fonts.css`).
TOP = 1250
HEIGHT = 1600


def specimen(path: Path, scale: float) -> tuple[int, str]:
    font = TTFont(path)
    font.flavor = None
    data = io.BytesIO()
    font.save(data)

    face = hb.Face(data.getvalue())
    hb_font = hb.Font(face)
    buffer = hb.Buffer()
    buffer.add_str(WORD)
    buffer.guess_segment_properties()
    hb.shape(hb_font, buffer, {"kern": True, "liga": True})

    upem = font["head"].unitsPerEm
    unit = 1000 * scale / upem
    glyphs = font.getGlyphSet()
    order = font.getGlyphOrder()
    pen = SVGPathPen(glyphs, ntos=lambda n: f"{round(n)}")
    x = 0.0
    for info, pos in zip(buffer.glyph_infos, buffer.glyph_positions):
        name = order[info.codepoint]
        transform = (unit, 0, 0, -unit, (x + pos.x_offset) * unit, -pos.y_offset * unit)
        glyphs[name].draw(TransformPen(pen, transform))
        x += pos.x_advance
    return round(x * unit), pen.getCommands()


def main() -> None:
    lines = [
        "// Generated by `scripts/font-specimens.py`: do not edit.",
        "",
        "/**",
        f" * The word {WORD} in some reading fonts, as SVG paths (in thousandths of an",
        " * em, the baseline at 0, each font scaled like in `fonts.css`), for the",
        " * about page: drawn, the specimens download none of the fonts.",
        " */",
        "export const fontSpecimens = {",
        f"  word: \"{WORD}\",",
        f"  viewBoxTop: -{TOP},",
        f"  viewBoxHeight: {HEIGHT},",
        "  fonts: [",
    ]
    for name, file, scale in SPECIMENS:
        width, d = specimen(FONTS / file, scale)
        lines += [
            "    {",
            f"      name: \"{name}\",",
            f"      width: {width},",
            f"      d: \"{d}\",",
            "    },",
        ]
    lines += ["  ],", "};", ""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUTPUT.relative_to(ROOT)}: {OUTPUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
